### ISSUE TITLE
AuthSdkError: Oauth flow response state doesn't match request state. When open multiple tabs on browser

### ISSUE THREAD

**Issue by HaofangLiu** [okta/okta-react#43] opened 2020-11-17 12:20 UTC
## I'm submitting this issue for the package(s):

- [x] okta-react

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

when open multiple tabs/pages concurrently, some of the tabs will get an 'AuthSdkError: Oauth flow response state doesn't match request state.'

## Expected behavior

all the tabs should be opened without any sdk issue.

## Minimal reproduction of the problem with instructions

I'm using react 16.12 and the pkce set as true on auth setting passed to security component. Regarding this issue still is not stable case to reproduce and cannot locate the specific issue. I will try different ways of testing.

## Environment

- Package Version:3.0.10
- Browser: google chrome Version 86.0.4240.198 (Official Build) (64-bit)
- OS: Windows
- Node version (`node -v`): v12.18.0
- Other:

Thanks for the information.

**Comment by oleksandrpravosudko-okta** [comment] 2020-11-17 13:59
Thanks for reporting this @HaofangLiu. It looks like similar [issue](https://github.com/okta/okta-oidc-js/issues/322) was reported before and it was expected to be fixed in v3.0.6 - I am going to check with developers involved in creating a fix to see if some follow-up work remains to be done

**Comment by oleksandrpravosudko-okta** [comment] 2020-11-17 15:04
@HaofangLiu, the underlying issue is fixed in [okta-auth-js v4.1.0](https://github.com/okta/okta-auth-js/blob/master/CHANGELOG.md#410) and will be available in okta-react v4

**Comment by HaofangLiu** [comment] 2020-11-18 08:20
> @HaofangLiu, the underlying issue is fixed in [okta-auth-js v4.1.0](https://github.com/okta/okta-auth-js/blob/master/CHANGELOG.md#410) and will be available in okta-react v4

Thanks for the reply. How soon will release the version 4 of okta-react?

**Comment by oleksandrpravosudko-okta** [comment] 2020-11-18 09:06
the work for bumping okta-auth-js dependency is happening this sprint, though the release date is TBD(expecting it soonish)

**Comment by tamarasaurus** [comment] 2020-11-25 09:17
Hey @oleksandrpravosudko-okta has this issue been fixed in this release? https://github.com/okta/okta-react/releases/tag/okta-react-4.0.0 I don't see it in the changelog

**Comment by oleksandrpravosudko-okta** [comment] 2020-11-25 10:34
hi @tamarasaurus - yes, okta-react-4.0.0 contains a fix for this issue
pardon for confusion - it might not have been included into changelog as a bugfix since the changeset resolving this issue was tracked as okta-auth-js [feature](https://github.com/okta/okta-auth-js/blob/master/CHANGELOG.md#features-1) - [#478](https://github.com/okta/okta-auth-js/pull/478)

**Comment by HaofangLiu** [comment] 2020-11-30 04:27
Hi @oleksandrpravosudko-okta, I try to upgrade to 4.0 version but how should I use the authservice.setFromUri() in previous version? I tried using oktaAuth instance with pre-configured from okta-auth-js, then call setOriginalUri(). but after /implicit/callback, it cannot redirect back to application. Do you have any idea what may cause this issue?

**Comment by oleksandrpravosudko-okta** [comment] 2020-11-30 09:02
Hi @HaofangLiu
can you please share the details of your oktaAuth instance usage?
in case you are using [`signInWithRedirect`](https://github.com/okta/okta-auth-js#signinwithredirectoptions) - does passing `originalUri` option work for you?

**Comment by HaofangLiu** [comment] 2020-12-01 09:35
Hi@oleksandrpravosudko-okta, Here is some of the usage in my app: 
I got a customized Logincallback component
```javascript
const LoginCallback = () => {
  const { oktaAuth, authState } = useOktaAuth();
  const authStateReady = !authState.isPending;

  useEffect(() => {
    oktaAuth.handleLoginRedirect();
  }, [oktaAuth]);

  if (authStateReady && authState.error) {
    if (authState.error.name && authState.error.message) {
      return <p>{authState.error.name}: {authState.error.message}</p>;
    }
    return <p>Error: {authState.error.toString()}</p>;
  }

  return null;
};

export default LoginCallback;
```

and I got an OktaAuth instance:
```javascript
const authObj = new OktaAuth ({
issuer: oktaConfig.oidc[config].issuer,
clientId: oktaConfig.oidc[config].clientId,
redirectUri: window.location.origin + '/implicit/callback',
scopes: ['openid', 'profile', 'email'],
pkce: oktaConfig.oidc[config].pkce,
postLogoutRedirectUri: window.location.origin,
tokenManager: {
            autoRenew: true,
            storage: 'sessionStorage' 
          }
})
```
For the top component Security params, the okta Auth instance has passed as required,but the onAuthRequired is not passed (as previous design)

* I replace
`authService.redirect({sessionToken: token}) `
to 
`oktaAuth.signInWithRedirect({sessionToken: token})`

* `authService.login(window.location.pathname + window.location.search)`
replace to
`oktaAuth.signInWithRedirect({ originalUri: window.location.pathname + window.location.search });`

* `authService.setFromUri(window.location.href)`
replace to 
`oktaAuth.setOriginalUri(window.location.href);`

 
The current behavior is after redirect back from /implicit/callback to localhost:8080 there is no further loading(stuck somewhere but these set of logic on previous 3.0.x version works fine, still trying to locate which caused this issue)

Is there anything I did wrong on these migration steps? or more likely it's some inside logic issue in my app?
Thanks for your time and help!

**Comment by oleksandrpravosudko-okta** [comment] 2020-12-01 11:59
thanks for providing the details, @HaofangLiu 

just to make sure I get it correctly - does the application advance past `/implicit/callback` URL? (i.e. is there a `/token` request happening/are there tokens set in sessionStorage?)

have you had a chance to look into [sample app's](https://github.com/okta/samples-js-react/tree/master/okta-hosted-login) usage of oktaAuth instance? (it doesn't feature explicit `setOriginalUri` usage but might point out other API methods invocation inconsistencies if there are any)

**Comment by aarongranick-okta** [comment] 2020-12-01 16:19
@HaofangLiu Can you post your react router configuration?

**Comment by HaofangLiu** [comment] 2020-12-02 09:48
@oleksandrpravosudko-okta the answer is yes, there is a `/token` request, and the token has set in sessionStorage.
I will try on sample to see if any help.

@aarongranick-okta the router I use origin router generated PrivateRoute as Route (https://github.com/jhipster/jhipster-sample-app-react/blob/main/src/main/webapp/app/shared/auth/private-route.tsx) in app.

**Comment by mraible** [comment] 2020-12-02 16:53
@HaofangLiu You linked to a JHipster file. You don't happen to be using JHipster, do you? I ask because I work on the project and help maintain its OAuth and OIDC support.

**Comment by HaofangLiu** [comment] 2020-12-03 04:47
@mraible Hi, yes the project is built by jhipster scaffold. is there any sample application use okta-react v4 to do the authentication? as aarongranick and oleksandrpravosudko's reply, I am wondering if there is some issues regarding the route issue.

Cheers

**Comment by mraible** [comment] 2020-12-03 06:23
If that's the case, you don't need okta-react. A generated JHipster app is
pre-configured to do all its OAuth flows with Spring Security. It's more
secure that way and doesn't require you to store an access token on the
client.

Is there a reason you want to change from the server side mechanism to the
(less secure) client-side version?

**Comment by nryoung** [comment] 2020-12-07 15:39
I recently upgraded my application to `3.0.10` and my users are hitting this much more frequently now and I can confirm they do not have multiple tabs open. Is the recommendation to bump `okta-react` to `4.0.0`? Is it confirmed this will fix the issue?

**Comment by swiftone** [comment] 2020-12-07 16:37
@nryoung - The discussion here is specific to multiple tabs, and okta-react 4.1.x is the recommended fix.

If you're seeing this problem with single tabs, it is likely that you have some race condition in your application that where multiple login processes are started.  4.1.x COULD address this - we introduced a queueing mechanism as well as the cross-tab communications - but without knowing how your code is triggering such a race condition I can't be certain the newer library would resolve it.

If you do decide to bump to 4.1.x, please note that 3.x to 4.x contains some breaking changes, so check the migration tips: https://github.com/okta/okta-react/blob/okta-react-4.0.0/README.md#migrating-from-3x-to-4x

**Comment by nryoung** [comment] 2020-12-07 17:09
@swiftone I actually modified my post as one of my users incorrectly told me that they only had one tab open.

Is there any consideration on backporting this fix to v3? Or is the fix the breaking change here?

**Comment by swiftone** [comment] 2020-12-07 17:26
We aren't planning on backporting the changes - technically I think it could be done without a breaking change, but we'd be repeating large portions of okta-auth-js code in okta-react (and okta-vue, and okta-angular) and those repeated code integrations would bring in lots of new potential for bugs.

The move from v3 to v4 of okta-react thins the client of okta-react and relies more on the state from okta-auth-js (which was internally included in previous versions and is now explicitly initialized and passed in v4)

**Comment by nryoung** [comment] 2020-12-09 22:49
@swiftone just wanted to report that we upgraded to `4.1.0` and we haven't seen this error in over 24 hours. So the recommended fix is working well so far!

**Comment by swiftone** [comment] 2020-12-09 22:55
@nryoung - Excellent!  And thanks for letting us know.  As the original poster looks to be resolved by virtue of making okta-react moot, I'll close this issue out in a couple of days if you've not seen problems before then.

**Comment by swiftone** [comment] 2020-12-23 18:27
Closing this as issues appear to have been resolved

**Closed by swiftone** 2020-12-23 18:27 UTC
