### ISSUE TITLE
Unhandled Rejection (TypeError): Object(...) is not a function

### ISSUE THREAD

**Issue by sumit194** [okta/okta-react#64] opened 2020-12-17 09:22 UTC
![image](https://user-images.githubusercontent.com/21281988/102467548-6d5c0d80-4076-11eb-83a3-e0b4c996244d.png)

Getting this error while loading the app first time after login redirect, but when manually try to remove the implicit/callback and reload the application it loads fine

After investigating I found out that the issue might be in https://github.com/okta/okta-react/blob/3270dda045fc0558fb2c51963f8d7c2e18d78553/src/Security.tsx#L47 this condition as it attaches the default restoreOriginalUri after the first load, that's why it works fine after removing the implicit/callback manually, also if I add restoreOriginalUri method in OktaAuth then it is working fine

Should we keep this https://github.com/okta/okta-react/blob/3270dda045fc0558fb2c51963f8d7c2e18d78553/src/Security.tsx#L47 condition out of useEffect as well, not sure if there is some other logic behind keeping it in useEffect only

@okta/okta-auth-js: 4.2.0
@okta/okta-react: 4.0.0

Thanks

**Comment by oleksandrpravosudko-okta** [comment] 2020-12-17 13:22
thanks for submission @sumit194 

I wasn't able to reproduce this error using a barebones app w/ specified package versions. Can you post more details on auth API you are using(e.g. signInWithRedirect) + your router configuration?

**Comment by shuowu** [comment] 2020-12-17 15:46
@sumit194 The default `restoreOriginalUri` callback function uses history API from `react-router-dom`, have you included the module in your dependencies? 

You can also override the default implementation by following [this guide](https://github.com/okta/okta-auth-js#restoreoriginaluri).

**Comment by sumit194** [comment] 2020-12-21 05:17
Hi @oleksandrpravosudko-okta  below are the implementation of my Okta Auth component
```
const ProtectedRoute = ({ children, ...rest }) => (
  <Suspense fallback={<div>loading...</div>}>
    <OktaComponent {...rest}>{children}</OktaComponent>
  </Suspense>
);

const OktaProvider = (props) => {
  const history = useHistory();
  const oktaAuth = new OktaAuth({
    issuer: config.okta.issuer,
    clientId: config.okta.client_id,
    redirectUri: config.okta.redirect_uri,
    restoreOriginalUri: async (_, originalUri) => {
      history.replace(toRelativeUrl(originalUri, window.location.origin));
    },
  });
  return (
    <Security oktaAuth={oktaAuth}>
      <SecureRoute path="/">
        <ProtectedRoute {...props} />
      </SecureRoute>
      <Route path="/implicit/callback">
        <LoginCallback />
      </Route>
    </Security>
  );
};
```
Now it is working fine, but if I remove the `restoreOriginalUri` from the `oktaAuth` then it throws the above error in first load

@shuowu yes I have react-router-dom as a dependency in my project, and after overriding the `restoreOriginalUrl` method it is working fine, but that should work without overriding as well

**Comment by shuowu** [comment] 2020-12-21 05:53
@sumit194 Can you try to move the oktaAuth initialization outside of the OktaProvider? As it may end up with creating more than one oktaAuth instances, which is not expected and may cause weird errors.

**Comment by sumit194** [comment] 2020-12-21 13:14
@shuowu before it was like that only, but after getting this issue I have to move it inside the component to use the `history` in `restoreOriginalUrl`

**Comment by shuowu** [comment] 2020-12-21 20:12
@sumit194 The error looks like a module export issue, but I cannot tell how it relevant with override the restoreOriginalUrl callback. Can you try our [official sample](https://github.com/okta/samples-js-react) to see if you can repro the issue there?

**Comment by sumit194** [comment] 2020-12-22 07:30
@shuowu sure, I'll try that, also can you please explain more about the module export issue (any specific component at okta package side or project side)

**Comment by shuowu** [comment] 2020-12-22 16:15
@sumit194 I saw some related issues by searching the error (https://github.com/facebook/react/issues/14484). You can check the details in the linked thread.

**Comment by jchabotamica** [comment] 2021-01-12 14:58
I believe @sumit194  is referring to circular dependencies with exports/imports.

**Comment by radicand** [comment] 2021-03-01 16:34
For anyone still tracking this, I had this issue as well, and it was because my `<Security>` block was outside the `<Router>` block. After nesting `<Security>` inside `<Router>` the issue went away.

**Comment by shuowu** [comment] 2021-06-17 13:33
@sumit194 Does @radicand 's comment above help?

**Comment by shuowu** [comment] 2021-06-17 13:37
Close the issue for now, feel free to reopen it if the issue still exist.

**Closed by shuowu** 2021-06-17 13:37 UTC
